apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
spec:
  nodeSelector:
    dedicated: web
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "web"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx